FROM gitlab/gitlab-ce:latest

MAINTAINER Pavlov <ppavlov@dontmail.me>

LABEL name="gitlab-ce"
LABEL version="2.107"
LABEL maintainer "ppavlov@dontmail.me"
LABEL architecture="x86_64"

ADD gitlab.rb /etc/gitlab/gitlab.rb
