version: '3.1'

services:
  jenkins:
    image: quay.io/ppavlov/jenkins-master
    networks:
      - default
      - traefik-net
    deploy:
      replicas: 1
      labels:
        - "traefik.port=8080"
        - "traefik.docker.network=traefik-net"
        - "traefik.frontend.rule=Host:jenkins.traefik"
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
      placement:
        constraints: [node.role == worker]
    volumes:
      - jenkins_home:/var/jenkins_home
    ports:
      - 50000:50000
    secrets:
      - jenkins-user
      - jenkins-pass
    restart: always
secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true
volumes:
    jenkins_home:
networks:
  traefik-net:
    external: true
