version: '3.6'

services:

  postgres:
    image: postgres
    ports:
     - 5432:5432
    environment:
     - POSTGRES_DB=artifactory
     # The following must match the DB_USER and DB_PASSWORD values passed to Artifactory
     - POSTGRES_USER=artifactory
     - POSTGRES_PASSWORD=password
    #volumes:
    # - postgres:/var/lib/postgresql/data
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3    
      placement:
        constraints: [node.role != manager]

  artifactory:
    image: jfrog-docker-reg2.bintray.io/jfrog/artifactory-pro:latest
    ports:
     - 8081:8081
    depends_on:
     - postgres
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints: [node.role != manager]
    volumes:
     - artifactory:/var/opt/jfrog/artifactory
    environment:
     - DB_TYPE=postgresql
     # The following must match the POSTGRES_USER and POSTGRES_PASSWORD values passed to PostgreSQL
     - DB_USER=artifactory
     - DB_PASSWORD=password
     # Adding extra Java options by uncommenting the following line
     #- EXTRA_JAVA_OPTIONS=-Xmx4g

  nginx:
    image: jfrog-docker-reg2.bintray.io/jfrog/reg2/jfrog/nginx-artifactory-pro:latest
    ports:
     - 80:80
     - 443:443
    depends_on:
     - artifactory
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints: [node.role != manager]
    volumes:
     - artifactory:/var/opt/jfrog/nginx
    environment:
     - ART_BASE_URL=http://artifactory:8081/artifactory
     - SSL=true

volumes:
  artifactory:
