version: "3.3"
services:
  portainer:
    image: portainer/portainer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
#      - "portainerdata:/data"
    networks:
      - traefik_traefik-net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.port=9000"
        - "traefik.docker.network=traefik_traefik-net"
        - "traefik.frontend.rule=Host:portainer.traefik"
networks:
  traefik_traefik-net:
    external: true
